version: '2'
services:
  codescene-ci-cd:
    build: . 
    ports:
      - "3005:3005"
    # Transfer environment variables from host to container
    # Set them on the host or use a .env file for specifying them
    environment:
      - CODESCENE_URL=${CODESCENE_URL}
      - CODESCENE_USER=${CODESCENE_USER}
      - CODESCENE_PASSWORD=${CODESCENE_PASSWORD}
      - CODESCENE_CI_CD_GITHUB_SECRET=${CODESCENE_CI_CD_GITHUB_SECRET}
      - CODESCENE_CI_CD_AZURE_TOKEN=${CODESCENE_CI_CD_AZURE_TOKEN}
      - CODESCENE_CI_CD_BITBUCKET_USER=${CODESCENE_CI_CD_BITBUCKET_USER}
      - CODESCENE_CI_CD_BITBUCKET_APP_PASSWORD=${CODESCENE_CI_CD_BITBUCKET_APP_PASSWORD}
